import { z } from "zod";

export const SeriesSeasonScheduleSchema = z.object({
  success: z.boolean(),
  season_id: z.number(),
  schedules: z.array(
    z.object({
      season_id: z.number(),
      race_week_num: z.number(),
      car_restrictions: z.array(
        z.object({
          car_id: z.number(),
          max_dry_tire_sets: z.number(),
          max_pct_fuel_fill: z.number(),
          power_adjust_pct: z.number(),
          race_setup_id: z.number(),
          weight_penalty_kg: z.number(),
        }),
      ),
      category: z.string(),
      category_id: z.number(),
      enable_pitlane_collisions: z.boolean(),
      full_course_cautions: z.boolean(),
      qual_attached: z.boolean(),
      qual_time_descriptors: z.array(z.null()),
      race_lap_limit: z.number(),
      race_time_descriptors: z.array(
        z.object({
          day_offset: z.array(z.number()),
          first_session_time: z.string(),
          repeat_minutes: z.number(),
          repeating: z.boolean(),
          session_minutes: z.number(),
          start_date: z.string(),
          super_session: z.boolean(),
        }),
      ),
      race_time_limit: z.number(),
      race_week_car_class_ids: z.array(z.number().optional()),
      race_week_cars: z.array(z.string().optional()),
      restart_type: z.string(),
      schedule_name: z.string(),
      season_name: z.string(),
      series_id: z.number(),
      series_name: z.string(),
      short_parade_lap: z.boolean(),
      special_event_type: z.null(),
      start_date: z.string(),
      start_type: z.string(),
      start_zone: z.boolean(),
      track: z.object({
        category: z.string(),
        category_id: z.number(),
        track_id: z.number(),
        track_name: z.string(),
      }),
      track_state: z.object({
        leave_marbles: z.boolean(),
      }),
      weather: z.object({
        data: z.object({
          allow_fog: z.boolean(),
          forecast_options: z.object({
            allow_fog: z.boolean(),
            forecast_type: z.number(),
            precipitation: z.number(),
            skies: z.number(),
            stop_precip: z.number(),
            temperature: z.number(),
            weather_seed: z.number(),
            wind_dir: z.number(),
            wind_speed: z.number(),
          }),
          precip_option: z.number(),
          rel_humidity: z.number(),
          simulated_start_time: z.string(),
          simulated_time_multiplier: z.number(),
          simulated_time_offsets: z.array(z.number()),
          skies: z.number(),
          temp_units: z.number(),
          temp_value: z.number(),
          time_of_day: z.number(),
          track_water: z.number(),
          version: z.number(),
          weather_summary: z.object({
            max_precip_rate: z.number(),
            max_precip_rate_desc: z.string(),
            precip_chance: z.number(),
            skies_high: z.number(),
            skies_low: z.number(),
            temp_high: z.number(),
            temp_low: z.number(),
            temp_units: z.number(),
            wind_dir: z.number(),
            wind_high: z.number(),
            wind_low: z.number(),
            wind_units: z.number(),
          }),
          weather_url: z.string(),
          wind_dir: z.number(),
          wind_units: z.number(),
          wind_value: z.number(),
        }),
      }),
      week_end_time: z.string(),
    }),
  ),
});
