import { z } from "zod";

export const SeriesSeasonListSchema = z.object({
  season_id: z.number().optional(),
  season_name: z.string().optional(),
  active: z.boolean(),
  allowed_season_members: z.null(),
  car_class_ids: z.array(z.number()),
  car_switching: z.boolean(),
  car_types: z
    .array(
      z.object({
        car_type: z.string(),
      }),
    )
    .optional(),
  caution_laps_do_not_count: z.boolean().optional(),
  complete: z.boolean().optional(),
  connection_black_flag: z.boolean(),
  consec_caution_within_nlaps: z.number(),
  consec_cautions_single_file: z.boolean(),
  cross_license: z.boolean(),
  current_week_sched: z.object({
    race_week_num: z.number(),
    track: z.object({
      category: z.string(),
      category_id: z.number(),
      track_id: z.number(),
      track_name: z.string(),
    }),
    car_restrictions: z.array(z.unknown()),
    race_lap_limit: z.number(),
    race_time_limit: z.null(),
    precip_chance: z.number(),
    start_type: z.string(),
    category_id: z.number(),
  }),
  distributed_matchmaking: z.boolean(),
  driver_change_rule: z.number(),
  driver_changes: z.boolean().optional(),
  drops: z.number().optional(),
  elig: z.object({
    own_car: z.boolean(),
    own_track: z.boolean(),
  }).optional(),
  enable_pitlane_collisions: z.boolean().optional(),
  fixed_setup: z.boolean().optional(),
  green_white_checkered_limit: z.number().optional(),
  grid_by_class: z.boolean().optional(),
  hardcore_level: z.number().optional(),
  has_mpr: z.boolean().optional(),
  has_supersessions: z.boolean().optional(),
  ignore_license_for_practice: z.boolean().optional(),
  incident_limit: z.number().optional(),
  incident_warn_mode: z.number().optional(),
  incident_warn_param1: z.number().optional(),
  incident_warn_param2: z.number().optional(),
  is_heat_racing: z.boolean().optional(),
  license_group: z.number().optional(),
  license_group_types: z.array(
    z.object({
      license_group_type: z.number(),
    }),
  ).optional(),
  lucky_dog: z.boolean().optional(),
  max_team_drivers: z.number().optional(),
  max_weeks: z.number().optional(),
  min_team_drivers: z.number().optional(),
  multiclass: z.boolean().optional(),
  must_use_diff_tire_types_in_race: z.boolean().optional(),
  num_fast_tows: z.number().optional(),
  num_opt_laps: z.number().optional(),
  official: z.boolean().optional(),
  op_duration: z.number().optional(),
  open_practice_session_type_id: z.number().optional(),
  qualifier_must_start_race: z.boolean().optional(),
  race_week: z.number().optional(),
  race_week_car_class_ids: z.array(
    z.object({
      race_week_num: z.number(),
      car_class_ids: z.array(z.number()),
    }),
  ).optional(),
  race_week_to_make_divisions: z.number().optional(),
  reg_user_count: z.number().optional(),
  region_competition: z.boolean().optional(),
  restrict_by_member: z.boolean().optional(),
  restrict_to_car: z.boolean().optional(),
  restrict_viewing: z.boolean().optional(),
  schedule_description: z.string().optional(),
  season_quarter: z.number().optional(),
  season_short_name: z.string().optional(),
  season_year: z.number().optional(),
  send_to_open_practice: z.boolean().optional(),
  series_id: z.number().optional(),
  short_parade_lap: z.boolean().optional(),
  start_date: z.string().optional(),
  start_on_qual_tire: z.boolean().optional(),
  start_zone: z.boolean().optional(),
  track_types: z
    .array(
      z.object({
        track_type: z.string(),
      }),
    )
    .optional(),
  unsport_conduct_rule_mode: z.number().optional(),
});
