import { GetSeasonsResponseType } from "./schema";

export const buildSeasonsData = (seasons: GetSeasonsResponseType[]) => {
  return seasons.map((season) => ({
    id: season.season_id,
    seriesId: season.series_id,
    seasonName: season.season_name,
    seasonShortName: season.season_short_name,
    seasonYear: season.season_year,
    seasonQuarter: season.season_quarter,
    active: season.active,
    complete: season.complete,
    official: season.official,
    licenseGroup: season.license_group,
    crossLicense: season.cross_license,
    ignoreLicenseForPractice: season.ignore_license_for_practice,
    maxWeeks: season.max_weeks,
    raceWeek: season.race_week,
    drops: season.drops,
    raceWeekToMakeDivisions: season.race_week_to_make_divisions,
    fixedSetup: season.fixed_setup,
    carSwitching: season.car_switching,
    multiclass: season.multiclass,
    restrictToCar: season.restrict_to_car,
    mustUseDiffTireTypes: season.must_use_diff_tire_types_in_race,
    startOnQualTire: season.start_on_qual_tire,
    incidentLimit: season.incident_limit,
    incidentWarnMode: season.incident_warn_mode,
    incidentWarnParam1: season.incident_warn_param1,
    incidentWarnParam2: season.incident_warn_param2,
    connectionBlackFlag: season.connection_black_flag,
    cautionLapsDoNotCount: season.caution_laps_do_not_count,
    consecCautionWithinNlaps: season.consec_caution_within_nlaps,
    consecCautionsSingleFile: season.consec_cautions_single_file,
    greenWhiteCheckeredLimit: season.green_white_checkered_limit,
    luckyDog: season.lucky_dog,
    shortParadeLap: season.short_parade_lap,
    startZone: season.start_zone,
    maxTeamDrivers: season.max_team_drivers,
    minTeamDrivers: season.min_team_drivers,
    driverChanges: season.driver_changes,
    driverChangeRule: season.driver_change_rule,
    qualifierMustStartRace: season.qualifier_must_start_race,
    enablePitlaneCollisions: season.enable_pitlane_collisions,
    gridByClass: season.grid_by_class,
    hardcoreLevel: season.hardcore_level,
    hasSupersessions: season.has_supersessions,
    isHeatRacing: season.is_heat_racing,
    opDuration: season.op_duration,
    openPracticeSessionTypeId: season.open_practice_session_type_id,
    numFastTows: season.num_fast_tows,
    numOptLaps: season.num_opt_laps,
    regionCompetition: season.region_competition,
    restrictByMember: season.restrict_by_member,
    restrictViewing: season.restrict_viewing,
    sendToOpenPractice: season.send_to_open_practice,
    distributedMatchmaking: season.distributed_matchmaking,
    unsportConductRuleMode: season.unsport_conduct_rule_mode,
    scheduleDescription: season.schedule_description,
    startDate: season.start_date,
    regUserCount: season.reg_user_count,
  }));
};


export const buildScheduleData = (
  schedules: GetSeasonsResponseType["schedules"],
) => {
  return schedules.map((schedule) => ({
    seasonId: schedule.season_id,
    raceWeekNum: schedule.race_week_num,
    scheduleName: schedule.schedule_name,
    seriesId: schedule.series_id,
    seriesName: schedule.series_name,
    category: schedule.category,
    categoryId: schedule.category_id,
    trackId: schedule.track.track_id,
    trackName: schedule.track.track_name,
    specialEventType: schedule.special_event_type || 0,
    sessionMinutes: schedule.race_time_descriptors[0]?.session_minutes || 0,
    tempUnit: schedule.weather.temp_units,
    tempValue: schedule.weather.temp_value,
    skies: schedule.weather.skies,
    windUnits: schedule.weather.wind_units,
    windValue: schedule.weather.wind_value,
    timeofDay: schedule.weather.time_of_day,
    trackWater: schedule.weather.track_water,
    allow_fog: schedule.weather.allow_fog,
    startDate: schedule.start_date,
    weekEndTime: schedule.week_end_time,
  }));
};
