import { GetSeasonsResponseType } from "./schema";

export const buildSeasonsData = (seasons: GetSeasonsResponseType[]) => {
  return seasons.map((season) => ({
    id: season.season_id,
    seriesId: season.series_id,
    seasonName: season.season_name,
    seasonShortName: season.season_short_name,
    seasonYear: season.season_year,
    seasonQuarter: season.season_quarter,
    active: season.active,
    complete: season.complete,
    official: season.official,
    licenseGroup: season.license_group,
    crossLicense: season.cross_license,
    maxWeeks: season.max_weeks,
    raceWeek: season.race_week,
    drops: season.drops,
    raceWeekToMakeDivisions: season.race_week_to_make_divisions,
    fixedSetup: season.fixed_setup,
    multiclass: season.multiclass,
    incidentLimit: season.incident_limit,
    incidentWarnMode: season.incident_warn_mode,
    incidentWarnParam1: season.incident_warn_param1,
    incidentWarnParam2: season.incident_warn_param2,
    connectionBlackFlag: season.connection_black_flag,
    maxTeamDrivers: season.max_team_drivers,
    minTeamDrivers: season.min_team_drivers,
    driverChanges: season.driver_changes,
    driverChangeRule: season.driver_change_rule,
    qualifierMustStartRace: season.qualifier_must_start_race,
    gridByClass: season.grid_by_class,
    opDuration: season.op_duration,
    openPracticeSessionTypeId: season.open_practice_session_type_id,
    numFastTows: season.num_fast_tows,
    numOptLaps: season.num_opt_laps,
    scheduleDescription: season.schedule_description,
    startDate: season.start_date,
    regUserCount: season.reg_user_count,
  }));
};

export const buildScheduleData = (
  schedules: GetSeasonsResponseType["schedules"],
) => {
  return schedules.map((schedule) => ({
    seasonId: schedule.season_id,
    raceWeekNum: schedule.race_week_num,
    scheduleName: schedule.schedule_name,
    seriesId: schedule.series_id,
    seriesName: schedule.series_name,
    category: schedule.category,
    categoryId: schedule.category_id,
    trackId: schedule.track.track_id,
    trackName: schedule.track.track_name,
    specialEventType: schedule.special_event_type || 0,
    sessionMinutes: schedule.race_time_descriptors[0]?.session_minutes || 0,
    tempUnit: schedule.weather.temp_units,
    tempValue: schedule.weather.temp_value,
    skies: schedule.weather.skies,
    windUnits: schedule.weather.wind_units,
    windValue: schedule.weather.wind_value,
    timeofDay: schedule.weather.time_of_day,
    trackWater: schedule.weather.track_water,
    allow_fog: schedule.weather.allow_fog,
    startDate: schedule.start_date,
    firstSessionTime:
      schedule.race_time_descriptors[0]?.first_session_time || "00:00:00",
    repeatMinutes: schedule.race_time_descriptors[0]?.repeat_minutes || 0,
    weekEndTime: schedule.week_end_time,
  }));
};
