import type { Metadata } from "next";

import { JetBrains_Mono } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/client";

import { Toaster } from "sonner";

import "./globals.css";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Git Gud Racing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body className={`${jetBrainsMono.className} antialiased`}>
          {children}

          <Toaster />
        </body>
      </html>
    </TRPCReactProvider>
  );
}
